import {
  AlertCircleIcon,
  AlertTriangleIcon,
  AnchorIcon,
  CalendarIcon,
  CarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsLeftIcon,
  ChevronsRightIcon,
  ChevronsUpDownIcon,
  ChevronUpIcon,
  CircleParkingIcon,
  ClockIcon,
  EditIcon,
  EyeIcon,
  EyeOffIcon,
  FileIcon,
  FilterIcon,
  FolderKanbanIcon,
  GridIcon,
  ImageMinusIcon,
  ImportIcon,
  InboxIcon,
  InfoIcon,
  InspectionPanelIcon,
  LayoutDashboardIcon,
  ListIcon,
  Loader2Icon,
  MoreHorizontalIcon,
  ParkingSquareIcon,
  PlusCircleIcon,
  PlusIcon,
  SaveIcon,
  SearchIcon,
  SettingsIcon,
  SlashIcon,
  SortAscIcon,
  SortDescIcon,
  TableIcon,
  TrashIcon,
  User2Icon,
  UserCog2Icon,
  UserRoundPlus,
  UsersIcon,
  WorkflowIcon,
  XIcon,
} from "lucide-react";

export const Icons = {
  spinner: Loader2Icon,

  slash: SlashIcon,

  // Sidebar
  overview: LayoutDashboardIcon,
  folder: FolderKanbanIcon,
  users: UsersIcon,
  vehicle: CarIcon,
  area: ParkingSquareIcon,
  dock: AnchorIcon,
  setting: SettingsIcon,
  manifest: ImportIcon,

  addParking: CircleParkingIcon,
  addUser: UserRoundPlus,
  inbox: InboxIcon,
  calendar: CalendarIcon,
  search: SearchIcon,

  moreH: MoreHorizontalIcon,
  edit: EditIcon,
  trash: TrashIcon,

  arrowSortUp: SortAscIcon,
  arrowSortDown: SortDescIcon,
  arrowUpDown: ChevronsUpDownIcon,
  doubleArrowLeft: ChevronsLeftIcon,
  doubleArrowRight: ChevronsRightIcon,
  arrowUp: ChevronUpIcon,
  arrowDown: ChevronDownIcon,
  arrowLeft: ChevronLeftIcon,
  arrowRight: ChevronRightIcon,

  eyeOff: EyeOffIcon,
  eye: EyeIcon,

  plusCircled: PlusCircleIcon,
  check: CheckIcon,
  x: XIcon,

  file: FileIcon,

  alertTriangle: AlertTriangleIcon,
  alertCircle: AlertCircleIcon,

  admin: UserCog2Icon,
  user: User2Icon,

  plus: PlusIcon,

  car: CarIcon,
  clock: ClockIcon,

  save: SaveIcon,

  filter: FilterIcon,

  grid: GridIcon,
  list: ListIcon,
  table: TableIcon,

  info: InfoIcon,
  workflow: WorkflowIcon,
  inspection: InspectionPanelIcon,
  photo: ImageMinusIcon,
};
