import {
    AlertCircleIcon,
    AlertTriangleIcon,
    AnchorIcon,
    CalendarIcon,
    CarIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronsLeftIcon,
    ChevronsRightIcon,
    ChevronsUpDownIcon,
    ChevronUpIcon,
    CircleParkingIcon,
    ClockIcon,
    EditIcon,
    EyeIcon,
    EyeOffIcon,
    FileIcon,
    FilterIcon,
    FolderKanbanIcon,
    GridIcon,
    ImageMinusIcon,
    InboxIcon,
    InfoIcon,
    InspectionPanelIcon,
    LayoutDashboardIcon,
    ListIcon,
    Loader2Icon,
    MoonIcon,
    MoreHorizontalIcon,
    ParkingSquareIcon,
    PlusCircleIcon,
    PlusIcon,
    SaveIcon,
    SearchIcon,
    SettingsIcon,
    SlashIcon,
    SortAscIcon,
    SortDescIcon,
    SunIcon,
    TableIcon,
    TrashIcon,
    User2Icon,
    UserCog2Icon,
    UserRoundPlus,
    UsersIcon,
    WorkflowIcon,
    XIcon,
} from "lucide-react";

export const Icons = {
    alertTriangle: AlertTriangleIcon,
    alertCircle: AlertCircleIcon,
    moon: MoonIcon,
    sun: SunIcon,

    overview: LayoutDashboardIcon,
    vehicle: CarIcon,
    area: ParkingSquareIcon,
    addParking: CircleParkingIcon,
    users: UsersIcon,
    addUser: UserRoundPlus,
    inbox: InboxIcon,
    calendar: CalendarIcon,
    search: SearchIcon,
    dock: AnchorIcon,
    setting: SettingsIcon,
    folder: FolderKanbanIcon,

    slash: SlashIcon,

    arrowSortUp: SortAscIcon,
    arrowSortDown: SortDescIcon,
    arrowUpDown: ChevronsUpDownIcon,
    doubleArrowLeft: ChevronsLeftIcon,
    doubleArrowRight: ChevronsRightIcon,
    arrowUp: ChevronUpIcon,
    arrowDown: ChevronDownIcon,
    arrowLeft: ChevronLeftIcon,
    arrowRight: ChevronRightIcon,

    eyeOff: EyeOffIcon,
    eye: EyeIcon,
    car: CarIcon,

    moreH: MoreHorizontalIcon,
    edit: EditIcon,
    trash: TrashIcon,

    plusCircled: PlusCircleIcon,
    plus: PlusIcon,
    check: CheckIcon,
    x: XIcon,

    admin: UserCog2Icon,
    user: User2Icon,

    spinner: Loader2Icon,

    fileIcon: FileIcon,
    file: FileIcon,

    // Nouvelles icônes pour le suivi
    clock: ClockIcon,
    info: InfoIcon,
    workflow: WorkflowIcon,
    inspection: InspectionPanelIcon,
    photo: ImageMinusIcon,
    save: SaveIcon,

    grid: GridIcon,
    list: ListIcon,
    table: TableIcon,
    filter: FilterIcon,
};
