import {
    AlertCircleIcon,
    CalendarIcon,
    CarIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronsUpDownIcon,
    EditIcon,
    EyeOffIcon,
    InboxIcon,
    LayoutDashboardIcon,
    Loader2Icon,
    MapPinIcon,
    MoonIcon,
    MoreHorizontalIcon,
    SearchIcon,
    SettingsIcon,
    SlashIcon,
    SortAscIcon,
    SortDescIcon,
    SunIcon,
    TrashIcon,
    User2Icon,
    UserCog2Icon,
    UserRoundPlus,
    UsersIcon,
} from "lucide-react";

export const Icons = {
    alertCircle: AlertCircleIcon,
    moon: MoonIcon,
    sun: SunIcon,

    overview: LayoutDashboardIcon,
    vehicle: CarIcon,
    area: MapPinIcon,
    users: UsersIcon,
    addUser: UserRoundPlus,
    inbox: InboxIcon,
    calendar: CalendarIcon,
    search: SearchIcon,
    setting: SettingsIcon,

    slash: SlashIcon,

    arrowUp: SortAscIcon,
    arrowDown: SortDescIcon,
    arrowUpDown: ChevronsUpDownIcon,
    arrowLeft: ChevronLeftIcon,
    doubleChevroLeft: ChevronLeftIcon,
    doubleChevroRight: ChevronRightIcon,
    arrowRight: ChevronRightIcon,
    eyeOff: EyeOffIcon,

    moreH: MoreHorizontalIcon,
    edit: EditIcon,
    trash: TrashIcon,

    admin: UserCog2Icon,
    user: User2Icon,

    spinner: Loader2Icon,
};
