import {
    AlertCircleIcon,
    AlertTriangleIcon,
    AnchorIcon,
    CalendarIcon,
    CarIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronsLeftIcon,
    ChevronsRightIcon,
    ChevronsUpDownIcon,
    ChevronUpIcon,
    CircleParkingIcon,
    EditIcon,
    EyeOffIcon,
    InboxIcon,
    LayoutDashboardIcon,
    Loader2Icon,
    MoonIcon,
    MoreHorizontalIcon,
    ParkingSquareIcon,
    PlusCircleIcon,
    SearchIcon,
    SettingsIcon,
    SlashIcon,
    SortAscIcon,
    SortDescIcon,
    SunIcon,
    TrashIcon,
    User2Icon,
    UserCog2Icon,
    UserRoundPlus,
    UsersIcon,
    XIcon,
} from "lucide-react";

export const Icons = {
    alertTriangle: AlertTriangleIcon,
    alertCircle: AlertCircleIcon,
    moon: MoonIcon,
    sun: SunIcon,

    overview: LayoutDashboardIcon,
    vehicle: CarIcon,
    area: ParkingSquareIcon,
    addParking: CircleParkingIcon,
    users: UsersIcon,
    addUser: UserRoundPlus,
    inbox: InboxIcon,
    calendar: CalendarIcon,
    search: SearchIcon,
    dock: AnchorIcon,
    setting: SettingsIcon,

    slash: SlashIcon,

    arrowSortUp: SortAscIcon,
    arrowSortDown: SortDescIcon,
    arrowUpDown: ChevronsUpDownIcon,
    doubleArrowLeft: ChevronsLeftIcon,
    doubleArrowRight: ChevronsRightIcon,
    arrowUp: ChevronUpIcon,
    arrowDown: ChevronDownIcon,
    arrowLeft: ChevronLeftIcon,
    arrowRight: ChevronRightIcon,

    eyeOff: EyeOffIcon,

    moreH: MoreHorizontalIcon,
    edit: EditIcon,
    trash: TrashIcon,

    plusCircled: PlusCircleIcon,
    check: CheckIcon,
    x: XIcon,

    admin: UserCog2Icon,
    user: User2Icon,

    spinner: Loader2Icon,
};
