import { HeaderWrapper } from "@/features/page/header-wrapper";
import { cn } from "@/lib/utils";
import Providers from "@/providers/providers";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geist = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body
        className={cn(geist.className, "antialiased, h-full flex flex-col")}
      >
        <Providers>
          <HeaderWrapper />
          <Toaster position="bottom-right" richColors />
          <main className="flex-1">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
