import { Toaster } from "@/components/ui/sonner";
import { HomeFooter } from "@/features/Home/page/home-footer";
import { HomeHeader } from "@/features/Home/page/home-header";
import { cn } from "@/lib/utils";
import Providers from "@/providers/providers";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geist = Geist({
    weight: "400",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning className="h-full">
            <body
                className={cn(
                    geist.className,
                    "antialiased, h-full flex flex-col"
                )}
            >
                <Providers>
                    <HomeHeader />
                    <Toaster position="bottom-right" richColors closeButton />
                    <main className="flex-1">{children}</main>
                    <HomeFooter />
                </Providers>
            </body>
        </html>
    );
}
