version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_HOST=db
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_DATABASE=n8n
      - DB_MYSQLDB_USER=smmc
      - DB_MYSQLDB_PASSWORD=smmc123
      - TZ=Africa/Nairobi
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db
    networks:
      - n8n-network

  db:
    image: mariadb:latest
    container_name: n8n-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=n8n
      - MYSQL_USER=smmc
      - MYSQL_PASSWORD=smmc123
      - TZ=Africa/Nairobi
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - n8n-network

volumes:
  n8n_data:
  mariadb_data:

networks:
  n8n-network:
    driver: bridge