version: "3.9"

services:
    nextjs:
        image: oven/bun:latest
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        command: "bun run dev"
